version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: shop_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 101204
      POSTGRES_DB: shopdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: shop_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com   # email login pgAdmin
      PGADMIN_DEFAULT_PASSWORD: admin         # password login pgAdmin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
